### ISSUE TITLE
getkeyvalues error

### ISSUE THREAD

**Issue by sophia-ooo** [nytlabs/gojee#5]
unexpected fault address 0x0
fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x40708e]

goroutine 3186217 [running]:
[fp=0x7f2d386dc380] runtime.throw(0x941e97)
    /usr/lib/go/src/pkg/runtime/panic.c:473 +0x67
[fp=0x7f2d386dc398] runtime.sigpanic()
    /usr/lib/go/src/pkg/runtime/os_linux.c:239 +0xe7
[fp=0x7f2d386dc400] runtime.mapaccess1_faststr()
    /usr/lib/go/src/pkg/runtime/hashmap.c:458 +0x2de
[fp=0x7f2d386dc6b8] github.com/nytlabs/gojee.getKeyValues(0xc201214fc0, 0x655840, 0xc2008fac00, 0xc2002a58d1, 0x7, ...)
    /home/ubuntu/go/src/github.com/nytlabs/gojee/jee.go:758 +0x1a4
[fp=0x7f2d386dcf80] github.com/nytlabs/gojee.Eval(0xc201214fc0, 0x655840, 0xc2008fac00, 0xc2002574b8, 0x2, ...)
    /home/ubuntu/go/src/github.com/nytlabs/gojee/jee.go:964 +0x322a
----- stack segment boundary -----
[fp=0x7f2d39f55f80] github.com/nytlabs/gojee.Eval(0xc200e32040, 0x655840, 0xc2008fac00, 0x65e300, 0x7f2d3865d600, ...)
    /home/ubuntu/go/src/github.com/nytlabs/gojee/jee.go:873 +0x758
----- stack segment boundary -----
[fp=0x7f2d386f2de0] github.com/nytlabs/gojee.Eval(0xc201214f80, 0x655840, 0xc2008fac00, 0xc2008fac00, 0xc2007f1578, ...)
    /home/ubuntu/go/src/github.com/nytlabs/gojee/jee.go:1000 +0x2f1a
[fp=0x7f2d386f2fb0] github.com/nytlabs/streamtools/blocks.Filter(0xc2003e1a80)
    /home/ubuntu/go/src/github.com/nytlabs/streamtools/blocks/filter.go:24 +0xdc
[fp=0x7f2d386f2fb8] runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1223
created by github.com/nytlabs/streamtools/daemon.(*Daemon).CreateBlock
    /home/ubuntu/go/src/github.com/nytlabs/streamtools/daemon/daemon.go:438 +0x310

**Comment by sophia-ooo** [comment]
cannot reproduce
